version: '3'

services:
  redis:
    image: redis:5.0-alpine3.8
    volumes:
      - redis:/data

  web:
    image: tyh835/hello-flask
    depends_on:
      - redis
    environment:
      - REDIS_CONTAINER_NAME=redis
    volumes:
      - static_files:/usr/src/app/public

  nginx:
    image: tyh835/hello-flask-nginx
    depends_on:
      - web
    ports:
      - 8080:80
    volumes:
      - static_files:/usr/share/nginx/html

volumes:
  redis:
  static_files:
