version: '3'

services:
  redis:
    image: redis:5.0-alpine3.8
    volumes:
      - redis:/data

  web:
    image: tyh835/hello-flask
    depends_on:
      - redis
    environment:
      - REDIS_CONTAINER_NAME=redis
    volumes:
      - ./public:/usr/src/app/public

  nginx:
    image: tyh835/hello-flask-nginx
    depends_on:
      - web
    volumes:
      - ./public:/tmp/nginx/html:ro
    ports:
      - 8080:80

volumes:
  redis:
