version: '3'

services:
  postgres:
    image: postgres:11.1-alpine
    environment:
      POSTGRES_USER: flask
      POSTGRES_PASSWORD: yourpassword
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data

  redis:
    image: redis:5.0-alpine
    ports:
      - 6379:6379
    volumes:
      - redis:/data

  app:
    image: tyh835/flask-redis-postgres
    ports:
      - 8000:8000

volumes:
  postgres:
  redis: